apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        livenessProbe:
          httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 5
        env:
        - name: MESSAGE
          value: "{{ .Values.message }}"


